task:
  name: TumorSegmentationTask
  params:
    backbone_name: efficientnet_b0
    backbone_params:
      in_chans: &num_channels 1
      pretrained: true
    heads:
      - type: Unet
        name: mask
        params:
          num_classes: 5
    use_ema: false
    input_size: [*num_channels, &height 196, &width 196]

criterion:
  criterion_list:
    - name: DiceLoss
      params:
        mode: multiclass
        target_fields:
          target: target_mask
          input: prediction_mask
    - name: LovaszLoss
      params:
        mode: multiclass
        target_fields:
          target: target_mask
          input: prediction_mask
    - name: CrossEntropyLoss
      params:
        target_fields:
          target: target_mask
          input: prediction_mask

optimizer:
  name: SGD
  params:
    lr: &initial_lr 0.03
    weight_decay: 0.00005
    momentum: 0.9
    nesterov: true


scheduler:
  name: CosineAnnealingWarmRestarts
  params:
    T_0: 5
    T_mult: 2

data:
  dataset_name: BRATSDataset
  common_params:
    data_folder: "../data"
    input_dtype: float16
  dataloader_params:
    batch_size: 16
    num_workers: 8
    shuffle: true
    drop_last: false

  train_params:
    params:
      path_to_datalist: "data_train_brats.csv"
    transform:
      - &normalize
        name: InstanceNormalize
      - &totensor
        name: ToTensorV2
    augment:
      - name: VerticalFlip
      - name: ShiftScaleRotate
        params:
          scale_limit: 0.3
          rotate_limit: 90
          shift_limit: 0.1
          border_mode: 0
          mask_value: 0
          value: 0
          p: 0.8
      - name: RandomResizedCrop
        params:
          height: *height
          width: *width
          scale: [0.5, 1.0]
          p: 0.5
#      - &pad
#        name: PadIfNeeded
#        params:
#          min_height: *height
#          min_width: *width
#          border_mode: 0
      - &resize
        name: Resize
        params:
          height: *height
          width: *width
      - name: OneOf
        params:
          transforms:
            - name: ElasticTransform
              params:
                alpha_affine: 0.05
            - name: GridDistortion
              params:
                distort_limit: 0.2
          p: 0.7

  valid_params:
    params:
      path_to_datalist: "data_valid_brats.csv"
    transform:
#      - *pad
      - *resize
      - *normalize
      - *totensor

trainer:
  gpus: 0
  max_epochs: 150
  train_percent_check: 1
  val_percent_check: 1
  progress_bar_refresh_rate: 1
  check_val_every_n_epoch: 1
  precision: 16

logger:
  save_dir: "logs/brats"
  name: unet_effnet_b0_in_fp16_s256

checkpoint:
  monitor: valid/loss
  save_last: true
  mode: min

profiler:
  name: simple
  save_profile: false

metrics:
  - name: MeanIntersectionOverUnionMeter
    params:
      name: mIoU_brats
      num_classes: 5
      average: global
      target_fields:
        target: target_mask
        prediction: prediction_mask
